[build]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"
  environment = "production"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  NODE_ENV = "production"

[context.production]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"
  environment = "production"

[context.production.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

[context.deploy-preview]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"
  environment = "production"

[context.branch-deploy]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"
  environment = "production"
