[build]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"

[context.production]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"

[context.deploy-preview]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"

[context.branch-deploy]
  base = "/"
  publish = "/frontend/dist"
  command = "yarn install && yarn add -D vite && cd frontend && yarn install && yarn build"
